# Generated by Django 5.2.2 on 2025-06-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='nome',
            new_name='nome_social',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='telefone',
        ),
        migrations.AddField(
            model_name='profissional',
            name='contato',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='profissional',
            name='endereco',
            field=models.CharField(default='Não informado', max_length=200),
        ),
        migrations.AddField(
            model_name='profissional',
            name='profissao',
            field=models.CharField(default='Não informado', max_length=100),
        ),
    ]
