# Generated by Django 5.2.2 on 2025-06-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='paciente',
        ),
    ]
